import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import fs from 'fs/promises';
import path from 'path';

export async function convertToPdf(inputPath: string, originalFilename: string): Promise<string | null> {
  try {
    // 模拟转换：创建一个简单的 PDF 文件
    // 在实际生产环境中，这里应该调用 LibreOffice 或其他转换服务

    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage();
    const { width, height } = page.getSize();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);

    page.drawText(`Preview for: ${originalFilename}`, {
      x: 50,
      y: height - 100,
      size: 24,
      font,
      color: rgb(0, 0, 0),
    });

    page.drawText('Note: This is a placeholder PDF generated by the system.', {
      x: 50,
      y: height - 150,
      size: 14,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });

    page.drawText('Real conversion requires server-side tools (e.g., LibreOffice).', {
      x: 50,
      y: height - 180,
      size: 14,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });

    const pdfBytes = await pdfDoc.save();

    const outputDir = path.dirname(inputPath);
    const outputFilename = path.basename(inputPath, path.extname(inputPath)) + '.pdf';
    const outputPath = path.join(outputDir, outputFilename);

    await fs.writeFile(outputPath, pdfBytes);

    // 返回相对 URL (假设 inputPath 是在 public/uploads 下)
    const relativePath = outputPath.split('public')[1].replace(/\\/g, '/');
    return relativePath;
  } catch (error) {
    console.error('PDF Conversion failed:', error);
    return null;
  }
}
